version: "3.9"

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:${PORT}"
  postgres:
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
  celery-worker:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
        DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    command: celery -A cooperation_island_37829 worker --loglevel=info       
    volumes:
      - ./:/opt/webapp

volumes: 
  postgres-data:

