# Generated by Django 2.2.28 on 2023-05-26 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230525_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentAccessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=100, unique=True, verbose_name='Access Code')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Expired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by_users', models.ManyToManyField(blank=True, related_name='access_codes_used', to=settings.AUTH_USER_MODEL, verbose_name='Used by Users')),
            ],
        ),
    ]
