# Generated by Django 2.2.28 on 2023-05-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_consentaccesscode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='avatar_id',
        ),
    ]
