# Generated by Django 2.2.28 on 2023-05-28 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230526_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='detail_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_month', models.IntegerField()),
                ('birth_year', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('zipcode', models.CharField(max_length=10)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
