# Generated by Django 2.2.28 on 2023-06-09 07:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_passwordresetsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
