# Generated by Django 2.2.28 on 2023-07-05 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230614_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('fish-mind-reading', 'Fish Mind Reading'), ('tree-shaking', 'Tree Shaking')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('text_input', 'Text Input'), ('multiple_choice', 'Multiple Choice Question'), ('dropdown', 'Dropdown Selection')], max_length=20)),
                ('activity_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='users.ActivityFeedback')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('activity_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ActivityFeedback')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('activity_feedback', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.ActivityFeedback')),
                ('answer_options', models.ManyToManyField(blank=True, to='users.AnswerOption')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Question')),
            ],
        ),
        migrations.CreateModel(
            name='FishGameTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_number', models.IntegerField()),
                ('match', models.BooleanField()),
                ('trial_response_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='users.Question'),
        ),
    ]
