# Generated by Django 2.2.28 on 2023-07-11 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230705_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeShakingGameTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_number', models.PositiveIntegerField()),
                ('shell', models.PositiveIntegerField()),
                ('shared_shell', models.PositiveIntegerField()),
                ('trial_response_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tree_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RankedQualities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.PositiveSmallIntegerField(choices=[(1, 'Being Honest'), (2, 'Being Funny'), (3, 'Being Stickler'), (4, 'Being Fair'), (5, 'Being Athletic'), (6, 'Being Generous'), (7, 'Being Intelligent'), (8, 'Being Artistic')])),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Very Important'), (2, 'A Little Important'), (3, 'Not That Important')])),
                ('rank', models.PositiveSmallIntegerField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
