# Generated by Django 2.2.28 on 2023-08-03 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20230719_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishgametrial',
            name='original_participant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualrankingqualitiesscore',
            name='original_participant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualrankingqualitiesscore',
            name='original_question_text',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participantresponse',
            name='original_participant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantresponse',
            name='original_question_text',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rankedqualities',
            name='original_participant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treeshakinggametrial',
            name='original_participant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityfeedback',
            name='activity_type',
            field=models.CharField(choices=[('fish-mind-reading', 'Fish Mind Reading'), ('tree-shaking', 'Tree Shaking'), ('tell-us-about-you', 'Tell Us About You')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='consentaccesscode',
            name='access_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Access Code'),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='verification_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='fishgametrial',
            name='participant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fishgametrial',
            name='trial_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='fishgametrial',
            name='trial_response_time',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='individualrankingqualitiesscore',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='individualrankingqualitiesscore',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Question'),
        ),
        migrations.AlterField(
            model_name='participantresponse',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participantresponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Question'),
        ),
        migrations.AlterField(
            model_name='passwordresetsession',
            name='session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text_input', 'Text Input'), ('multiple_choice', 'Multiple Choice Question'), ('dropdown', 'Dropdown Selection'), ('rating', 'Rating')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rankedqualities',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rankedqualities',
            name='quality',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Being Fair'), (2, 'Being Honest'), (3, 'Following the rules'), (4, 'Being Generous'), (5, 'Being funny'), (6, 'Being athletic'), (7, 'Being artistic'), (8, 'Being intelligent'), (9, 'Being forgiving'), (10, 'Standing up for others'), (11, 'Being trustworthy')]),
        ),
        migrations.AlterField(
            model_name='treeshakinggametrial',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree_participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treeshakinggametrial',
            name='trial_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='treeshakinggametrial',
            name='trial_response_time',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
