# Generated by Django 2.2.28 on 2023-08-25 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20230803_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeShakingDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='fishgametrial',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishgametrial',
            name='session_id',
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fishgametrial',
            name='shell',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualrankingqualitiesscore',
            name='session_id',
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantresponse',
            name='session_id',
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rankedqualities',
            name='session_id',
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treeshakinggametrial',
            name='session_id',
            field=models.CharField(default=0, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='shells',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='activityfeedback',
            name='activity_type',
            field=models.CharField(choices=[('fish-mind-reading', 'Fish Mind Reading'), ('tree-shaking', 'Tree Shaking'), ('voice-your-values', 'Voice Your Values')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text_input', 'Text Input'), ('multiple_choice', 'Multiple Choice Question'), ('dropdown', 'Dropdown Selection'), ('rating', 'Rating'), ('instruction', 'Instruction')], max_length=100),
        ),
        migrations.CreateModel(
            name='TreeShakingDistributionTrials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_number', models.PositiveIntegerField()),
                ('self_distribution', models.PositiveIntegerField()),
                ('partner_distribution', models.PositiveIntegerField()),
                ('tree_game_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.TreeShakingDistribution')),
            ],
        ),
        migrations.AddField(
            model_name='treeshakingdistribution',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treegame_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IncentiveRangeSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_level_selected', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incentive_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FishGameDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, unique=True)),
                ('min', models.PositiveIntegerField()),
                ('max', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fishgame_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
