# Generated by Django 2.2.28 on 2023-09-08 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20230825_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_prompts', to='users.ActivityFeedback')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text_input', 'Text Input'), ('multiple_choice', 'Multiple Choice Question'), ('dropdown', 'Dropdown Selection'), ('rating', 'Rating')], max_length=100),
        ),
        migrations.CreateModel(
            name='DynamicPromptResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dynamic_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DynamicPrompt')),
            ],
        ),
    ]
