# Generated by Django 2.2.28 on 2023-09-29 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20230908_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityfeedback',
            options={'verbose_name': 'Activity Type', 'verbose_name_plural': 'Activity Type'},
        ),
        migrations.AlterModelOptions(
            name='consentaccesscode',
            options={'verbose_name': 'Access Code'},
        ),
        migrations.AlterModelOptions(
            name='incentiverangeselection',
            options={'verbose_name_plural': 'Incentive Range Selection'},
        ),
        migrations.AlterModelOptions(
            name='individualrankingqualitiesscore',
            options={'verbose_name': 'Voice Your Values Rating'},
        ),
        migrations.AlterModelOptions(
            name='participantresponse',
            options={'verbose_name': 'End-of-Module Question Response'},
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name_plural': 'Privacy Policy'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User Profile Data', 'verbose_name_plural': 'User Profile Data'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'End-of-Module Question'},
        ),
        migrations.AlterModelOptions(
            name='questionorder',
            options={'verbose_name': 'End-of-Module Question Order'},
        ),
        migrations.AlterModelOptions(
            name='rankedqualities',
            options={'verbose_name_plural': 'Voice Your Values'},
        ),
        migrations.AddField(
            model_name='fishgametrial',
            name='participant_shell',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fishgametrial',
            name='stakes_max',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fishgametrial',
            name='stakes_min',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fishgametrial',
            name='stakes_type',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='treeshakinggametrial',
            name='participant_shell',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treeshakinggametrial',
            name='stakes_type',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='fishgametrial',
            name='shell',
            field=models.PositiveSmallIntegerField(verbose_name='Trial Incentive'),
        ),
        migrations.CreateModel(
            name='ThemeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.PositiveSmallIntegerField(choices=[(1, 'Ancient Ruins'), (2, 'Aqua Adventure'), (3, 'Celestial Voyager'), (4, 'Jungle Explorer'), (5, 'Moonlit Campfire'), (6, 'Mystical Enchantment'), (7, 'Pirate Adventure'), (8, 'Surf Up'), (9, 'Tropical Paradise')], unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='themeimage_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Theme Images',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=36)),
                ('original_participant_id', models.IntegerField(blank=True, null=True)),
                ('purchase_cost', models.PositiveIntegerField()),
                ('participant_shell_at_purchase', models.PositiveIntegerField()),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('theme_purchased', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.ThemeImage')),
            ],
            options={
                'verbose_name': 'Theme Purchase History',
                'verbose_name_plural': 'Theme Purchase History',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='purchased_themes',
            field=models.ManyToManyField(related_name='purchased_by', through='users.PurchaseHistory', to='users.ThemeImage'),
        ),
    ]
