# Generated by Django 2.2.28 on 2023-10-05 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20230929_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpromptresponse',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_prompt_responses', to='users.ActivityFeedback'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamicpromptresponse',
            name='original_participant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicpromptresponse',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
