# Generated by Django 2.2.28 on 2023-10-10 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20231005_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityfeedback',
            options={'verbose_name': 'End-of-Module Question Editable', 'verbose_name_plural': 'End-of-Module Question Editable'},
        ),
        migrations.AlterModelOptions(
            name='fishgametrial',
            options={'verbose_name': 'Fish game data', 'verbose_name_plural': 'Fish game data'},
        ),
        migrations.AlterModelOptions(
            name='individualrankingqualitiesscore',
            options={'verbose_name': 'Voice Your Values Rating Data', 'verbose_name_plural': 'Voice Your Values Rating Data'},
        ),
        migrations.AlterModelOptions(
            name='participantresponse',
            options={'verbose_name': 'End-of-Module Question Data', 'verbose_name_plural': 'End-of-Module Question Data'},
        ),
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'verbose_name': 'Experience Purchase History', 'verbose_name_plural': 'Experience Purchase History'},
        ),
        migrations.AlterModelOptions(
            name='rankedqualities',
            options={'verbose_name': 'Voice Your Values Category Data', 'verbose_name_plural': 'Voice Your Values Category Data'},
        ),
        migrations.AlterModelOptions(
            name='themeimage',
            options={'verbose_name': 'Experience Cost', 'verbose_name_plural': 'Experience Costs'},
        ),
        migrations.AlterModelOptions(
            name='treeshakinggametrial',
            options={'verbose_name': 'Tree shaking game data', 'verbose_name_plural': 'Tree shaking game data'},
        ),
        migrations.CreateModel(
            name='ThemeEmailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Email Subject')),
                ('body', models.TextField(verbose_name='Email Body')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Theme Email Configuration',
                'verbose_name_plural': 'Theme Email Configuration',
            },
        ),
        migrations.CreateModel(
            name='ConsentEmailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Email Subject')),
                ('body', models.TextField(verbose_name='Email Body')),
                ('token_expiry_days', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Email Configuration',
                'verbose_name_plural': 'Consent Email Configuration',
            },
        ),
        migrations.AddField(
            model_name='emailverification',
            name='email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ConsentEmailConfiguration'),
        ),
    ]
