# Generated by Django 2.2.28 on 2023-10-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20231010_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Assent Page Configuration', 'verbose_name_plural': 'Assent Page Configuration'},
        ),
        migrations.AlterModelOptions(
            name='termandcondition',
            options={'verbose_name': 'Consent Page Configuration', 'verbose_name_plural': 'Consent Page Configuration'},
        ),
        migrations.AddField(
            model_name='participantresponse',
            name='original_answer_options',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participantresponse',
            name='original_question_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
